# -*- coding: utf-8 -*-
"""PROJECT BATTERY RECOMMENDATION SYSTEM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_AD8TTTa4U2T13fXEM3qklAE1EHjy-Y
"""

import pandas as pd

data= pd.read_csv("ev_ameer.csv")
data

data.isnull().sum()

data= data.drop(columns=['Vehicle_ID'])



data.fillna(
    {
        'Autonomous_Level': data['Autonomous_Level'].median(),
        'Safety_Rating': data['Safety_Rating'].median(),
        'CO2_Emissions_g_per_km': 0
    },
    inplace=True
)

data.isnull().sum()

data=data.drop("CO2_Emissions_g_per_km", axis=1)

data.duplicated().sum()

if 'CO2_Emissions_g_per_km' in data.columns:
    data = data.drop(columns=['CO2_Emissions_g_per_km'])

data.shape

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor

data.hist(figsize=(12,12))
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

sns.scatterplot(data=data, x='Price_USD', y='Range_km')
plt.show()

sns.scatterplot(data=data, x='Battery_Capacity_kWh', y='Charge_Time_hr')
plt.show()

sns.boxplot(data=data, y='Price_USD')
plt.title('Boxplot of Price_USD')
plt.show()

numeric_cols = data.select_dtypes(include=['number']).columns

for col in numeric_cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(data=data, y=col)
    plt.title(f'Boxplot of {col}')
    plt.ylabel(col)
    plt.show()

data.info()

data.info()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ['Manufacturer', 'Model',
            'Charging_Type', 'Color',
            'Country_of_Manufacture']:
    data[col] = le.fit_transform(data[col])

data.info()




"""##NEW WEBSITE"""

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------
# SAMPLE BATTERY DATA
# ---------------------------

battery_data = pd.read_csv("ev_ameer.csv")
# ---------------------------
# RECOMMENDATION FUNCTION
# ---------------------------

def recommend_battery(budget, range_km, charge, warranty):

    filtered = battery_data[
        (battery_data["Price_USD"] <= budget) &
        (battery_data["Range_km"] >= range_km) &
        (battery_data["Charge_Time_hr"] <= charge) &
        (battery_data["Warranty_Years"] >= warranty)
    ]

    if filtered.empty:
        return "<p>No battery matches your requirements</p>", None, "Try adjusting filters", None

    top3 = filtered.sort_values(by="Range_km", ascending=False).head(3)

    # ---------------------------
    # CREATE CARDS
    # ---------------------------

    cards = ""

    for _, row in top3.iterrows():
        cards += f"""
        <div class="card">
        <h3>🔋 {str(row['Battery_Type'])}</h3>
        <p>⚡ Capacity: {row['Battery_Capacity_kWh']} kWh</p>
        <p>🚗 Range: {row['Range_km']} km</p>
        <p>⏱ Charge Time: {row['Charge_Time_hr']} hrs</p>
        <p>💰 Price: ${row['Price_USD']:.2f}</p>
        <p>🛡 Warranty: {row['Warranty_Years']} years</p>
        </div>
        """

    # ---------------------------
    # CREATE IMPROVED CHART
    # ---------------------------

    fig, ax = plt.subplots(figsize=(6,4))

    names = top3["Battery_Type"].tolist()
    ranges = top3["Range_km"].tolist()

    bars = ax.bar(range(len(names)), ranges, color="#16a34a", width=0.9)

    ax.set_xticks(range(len(names)))
    ax.set_xticklabels(names)

    ax.set_title("Battery Range Comparison", fontsize=14, fontweight="bold")
    ax.set_ylabel("Range (km)", fontsize=12)

    # Value labels
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width()/2,
            height + 3,
            f"{height}",
            ha='center',
            fontsize=11,
            fontweight="bold"
        )

    # Clean look
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")

    plt.tight_layout()

    best = f"""
<h2 style="color:#16a34a;font-weight:900;">
 Best Battery Recommendation
</h2>

<p>
<b>{top3.iloc[0]['Battery_Type']}</b> is the best match based on your requirements.
</p>
"""

    csv_file = "battery_report.csv"
    top3.to_csv(csv_file, index=False)

    return cards, fig, best, csv_file


# ---------------------------
# UI THEME
# ---------------------------

theme = gr.themes.Soft(
    primary_hue="green",
    neutral_hue="gray"
)

css = """
body{
background:white;
}

.gradio-container{
background:white !important;
}

img{
width:100%;
height:260px;
object-fit:cover;
}

h1,h2,h3{
color:black;
font-weight:800;
}

.hero{
text-align:center;
padding:20px;
}

.card{
background:#f8fafc;
padding:18px;
border-radius:10px;
margin:10px;
box-shadow:0 4px 10px rgba(0,0,0,0.1);
color:#000;
}

.card h3{
color:#000;
font-weight:700;
}

.card p{
color:#111827;
font-weight:500;
}
"""

# ---------------------------
# GRADIO APP
# ---------------------------

with gr.Blocks(theme=theme, css=css) as app:

    gr.Markdown("""
    <div class='hero'>
    <h1>⚡ EV Battery Recommendation System</h1>
    <p>AI-powered tool to find the best EV battery based on your requirements</p>
    </div>
    """)

    gr.Image(
        value="https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
        height=260,
        show_label=False,
        container=False
    )

    with gr.Row():

        with gr.Column(scale=1):

            gr.Markdown("### ⚙ Battery Requirements")

            budget = gr.Number(
                label="Maximum Budget ($)",
                value=None,
                minimum=30000,
                maximum=149999,
                placeholder="Enter budget [30000-149999]"
            )

            range_km = gr.Number(
                label="Minimum Range (km)",
                value=None,
                minimum=100,
                maximum=600,
                placeholder="Enter range [100-600]"
            )

            charge = gr.Number(
                label="Maximum Charge Time (hrs)",
                value=None,
                minimum=0.5,
                maximum=12.0,
                placeholder="Enter charge time [0.5-12.0]"
            )

            warranty = gr.Number(
                label="Minimum Warranty (years)",
                value=None,
                minimum=3,
                maximum=5,
                placeholder="Enter warranty years [3-5]"
            )

            submit = gr.Button("🔎 Recommend Battery")

        with gr.Column(scale=2):

            gr.Markdown("### 🔋 Top Battery Recommendations")
            card_output = gr.HTML()

            gr.Markdown("### 📊 Battery Performance Comparison")
            chart_output = gr.Plot()

            best_output = gr.Markdown()

            download_output = gr.File(label="📄 Download Recommendation Report")

            submit.click(
                fn=recommend_battery,
                inputs=[budget, range_km, charge, warranty],
                outputs=[card_output, chart_output, best_output, download_output]
            )

app.launch(share=True)

